import { Footer, Header } from '@/components'
import Providers from '@/context/providers'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App yeah',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="it">    
      <body className={inter.className}>  
        <Providers>
          {/* @ts-expect-error Server Component */}
          <Header/>
          {children}
          <Footer/>
        </Providers>
      </body>
    </html>
  )
}
