import { Header } from '@/components'
import './globals.css'

export const metadata = {
  title: 'Create Next App yeah',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="it">    
      <body>  
        <Header/>
        {children}
      </body>
    </html>
  )
}
