import './globals.css'
import { Banner, Carousel, Header } from '@/components'

export const metadata = {
  title: 'Create Next App yeah',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="it">    
      <body>  
        <Header/> 
        <Banner/>
        <Carousel/>
        {children}
      </body>
    </html>
  )
}
